### PR TITLE
Fix: Process never ends on error when use promise closes #98

### LINKED ISSUE #98: Process never ends on error when use promise
suppose following code is exist in a file named `test.js`:

```
const SVGFixer = require("oslllo-svg-fixer");
const options = {
    showProgressBar: true,
    throwIfDestinationDoesNotExist: false
};
const dirPath = "D:\\not-exist-folder";
SVGFixer(dirPath, dirPath, options)
    .fix()
    .then((result) => {
        console.log("Svg fixed", result);
    })
    .catch((error) => {
        console.log("Failed to fix", error);
    });
```

When you run the followin code:
```
node test.js
```
you will get this error which is correct:
```
    throw error.invalidPathError("source", source);
    ^

TypeError: source path D:\not-exist-folder does not exist.
    at Object.invalidPathError (D:\svgTestnode_modules\oslllo-svg-fixer\src\error.js:27:10)
    at new Location (D:\svgTestnode_modules\oslllo-svg-fixer\src\location.js:17:17)
    at new SVGFixer (D:\svgTestnode_modules\oslllo-svg-fixer\src\constructor.js:13:19)
    at SVGFixer (D:\svgTestnode_modules\oslllo-svg-fixer\src\constructor.js:10:12)
    at Object.<anonymous> (D:\svgTesttest2.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)

Node.js v20.11.0
```

But it will never exist the process and progress will not done.

After the following line this `this.teardown();` should called:
https://github.com/oslllo/svg-fixer/blob/b7e025a3d923db7607a3bc1af22ec2e3a7baa68a/src/processor.js#L60

### PR DESCRIPTION
**Pull request by sohrabi2050**
Fixing following issue: closes #98

### CODE REVIEW

**Comment by Ghustavh97** [comment]
Hi, thanks for the PR, please update the `browserslist` by running `npx browserslist@latest --update-db` to try and fix the failing tests.

**Comment by sohrabi2050** [comment]
Hi, Thanks,
Can you link the issue to this PR?
And when will the issues would be closed?
Regards

**Comment by Ghustavh97** [comment]
Hi, thanks for the PR, your fix will be available in `v4.0.0` that I will be releasing soon.

**Comment by Ghustavh97** [comment]
Your fix in now available in `v4.0.0`, thanks again for the PR.

**Pull request merged**
